### ISSUE TITLE
syncronize across tabs with localstorage

### ISSUE THREAD

**Issue by wiber** [jhen0409/react-chrome-extension-boilerplate#22]
Hi,

Updating the popup doesn't persist to localstore or propagate to other windows where the extension is running. How would I rerender all reacts when localstore changes? 

I'm looking to persist state to localstorage in a way similar to these: 

https://github.com/STRML/react-localstorage
http://stackoverflow.com/questions/21741754/react-js-syncing-entire-state-to-localstorage

I can then fire chrome.storage.onChanged.addListener but where does that go to reload the DOM(s) ?

Cheers,

Elias

**Comment by wiber** [comment]
If I understand redux (and do correct me if I'm wrong) persisting the actions to localstorage and applying them both from there and from the ui is the way to go? Or catching them up when window becomes active.

**Comment by zalmoxisus** [comment]
Yes, you are right, you have to persist redux states. Use [`redux-persist`](https://github.com/rt2zz/redux-persist) for that. To get it work with `chrome.storage` instead of `window.localStorage`, use [`chrome-storage-local`](https://github.com/zalmoxisus/chrome-storage-local). An example of configuration can be found [here](https://github.com/zalmoxisus/browser-redux/blob/master/src/app/store/getStoredState.js), which is used for [returning the store asynchronously](https://github.com/zalmoxisus/browser-redux/blob/master/src/app/store/configureStore.js).

**Comment by wiber** [comment]
Thanks @zalmoxisus , that looks good.
