### ISSUE TITLE
How would I add a content script?

### ISSUE THREAD

**Issue by Dottenpixel** [jhen0409/react-chrome-extension-boilerplate#73]
I have a need to manipulate the DOM in my extension and need a content script, but not sure how that fits in this structure

**Comment by 10S10** [comment]
@Dottenpixel  I had facing same issue as you. 

But Solution is here. 
add 
content.pug.
content.js 
and Reference this  .js file in to .pug file same as popup.js . 
Also don't forgot to mention content.js file in to menifest.dev.js -> entry point. 

If you are not mention right path then you will not get the .html file. 

All you need to just make content.js same way as popup.js.

**Comment by jhen0409** [comment]
We used [`chrome.tabs.executeScript`](https://developer.chrome.com/extensions/tabs#method-executeScript) instead of defined content script because we can't define the content script in development mode. See also: [`chrome/extension/background/inject.js`](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/chrome/extension/background/inject.js).

**Comment by HuangZurong** [comment]
![image](https://user-images.githubusercontent.com/1995132/61125486-8b662b80-a4dc-11e9-90b5-5d97360a36b8.png)
![image](https://user-images.githubusercontent.com/1995132/61125517-9caf3800-a4dc-11e9-85d5-615115319adb.png)
